"""
Remediation endpoints.

All routes require an authenticated user.

Endpoints:
  POST /remediation/triage-advice       — bulk triage plan (no enc context needed)
  POST /remediation/{vuln_id}/ticket    — draft a remediation ticket (enc context required)
"""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_llm_client, get_org_encryption
from app.core.encryption import FieldEncryption
from app.core.llm.base import LLMClient
from app.db.session import get_db
from app.models.user import User
from app.schemas.remediation import TicketDraftResponse, TicketRequest, TriageAdviceResponse
from app.services.enrichment import vulnerability_exists
from app.services.remediation import (
    JIRA_PRIORITY_MAP,
    bulk_triage_advice,
    draft_ticket,
)
from app.services.vulnerability import get_vulnerability

router = APIRouter()


# ── Triage advice (declared first to avoid routing conflict with /{vuln_id}) ──

@router.post(
    "/triage-advice",
    response_model=TriageAdviceResponse,
    status_code=status.HTTP_200_OK,
)
async def triage_advice(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    llm: LLMClient = Depends(get_llm_client),
) -> TriageAdviceResponse:
    """
    Generate a strategic triage plan for all scored vulnerabilities in the org.

    Reads only plaintext columns — no encryption context required.
    The LLM synthesises per-priority counts and top immediate vulnerabilities
    into an actionable Markdown plan.
    """
    advice = await bulk_triage_advice(db, llm, current_user.org_id)
    return TriageAdviceResponse(
        markdown=advice.markdown,
        total=advice.total,
        immediate_count=advice.immediate_count,
        this_week_count=advice.this_week_count,
        this_month_count=advice.this_month_count,
        monitor_count=advice.monitor_count,
        accept_count=advice.accept_count,
        unscored_count=advice.unscored_count,
    )


# ── Single-vulnerability ticket drafter ───────────────────────────────────────

@router.post(
    "/{vuln_id}/ticket",
    response_model=TicketDraftResponse,
    status_code=status.HTTP_200_OK,
)
async def draft_vuln_ticket(
    vuln_id: uuid.UUID,
    body: TicketRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    _enc: FieldEncryption = Depends(get_org_encryption),
    llm: LLMClient = Depends(get_llm_client),
) -> TicketDraftResponse:
    """
    Draft a remediation ticket for a single vulnerability.

    The ticket is generated by the LLM using the full vulnerability context
    (including encrypted fields — requires active encryption context).

    Query body:
      format             — "markdown" | "jira" | "both" (default: "both")
      create_jira_issue  — if true, POST to Jira when org has Jira configured

    Returns both Markdown and Jira-formatted fields.  When create_jira_issue=True
    and Jira is configured, jira_issue_key and jira_issue_url are populated.
    """
    vuln = await get_vulnerability(db, current_user.org_id, vuln_id)
    if vuln is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Vulnerability not found.",
        )

    ticket = await draft_ticket(llm, vuln)

    markdown = ticket.markdown if body.format in ("markdown", "both") else None
    jira_summary = ticket.jira_summary if body.format in ("jira", "both") else None
    jira_description = ticket.jira_description if body.format in ("jira", "both") else None
    jira_priority = ticket.jira_priority if body.format in ("jira", "both") else None

    jira_issue_key: str | None = None
    jira_issue_url: str | None = None

    if body.create_jira_issue:
        from sqlalchemy import select
        from app.models.organization import OrgSettings

        settings_row = await db.execute(
            select(OrgSettings).where(OrgSettings.org_id == current_user.org_id)
        )
        org_settings = settings_row.scalar_one_or_none()

        if (
            org_settings is None
            or not org_settings.jira_base_url
            or not org_settings.jira_project_key
            or not org_settings.encrypted_jira_api_key
        ):
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=(
                    "Jira integration is not configured. "
                    "Set jira_base_url, jira_project_key, and jira_api_key in org settings."
                ),
            )

        jira_api_key = _enc.decrypt(org_settings.encrypted_jira_api_key)

        try:
            from app.core.clients.jira import create_jira_issue

            result = await create_jira_issue(
                base_url=org_settings.jira_base_url,
                project_key=org_settings.jira_project_key,
                api_key=jira_api_key,
                summary=ticket.jira_summary,
                description=ticket.jira_description,
                priority=ticket.jira_priority,
            )
            jira_issue_key = result["key"]
            jira_issue_url = result["url"]
        except Exception as exc:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Failed to create Jira issue: {exc}",
            )

    return TicketDraftResponse(
        vuln_id=vuln_id,
        cve_id=vuln.cve_id,
        format=body.format,
        markdown=markdown,
        jira_summary=jira_summary,
        jira_description=jira_description,
        jira_priority=jira_priority,
        jira_issue_key=jira_issue_key,
        jira_issue_url=jira_issue_url,
    )
