"""Phase 6-8 scoring columns and audit log

Revision ID: 215638744cc4
Revises: 002
Create Date: 2026-04-15 23:06:23.189043

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215638744cc4'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.add_column('vulnerabilities', sa.Column('triage_priority', sa.String(length=20), nullable=True))
    op.add_column('vulnerabilities', sa.Column('enc_score_rationale', sa.Text(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_vulnerabilities_org_cve_source', table_name='vulnerabilities')
    op.create_index(op.f('ix_vulnerabilities_triage_priority'), 'vulnerabilities', ['triage_priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_triage_priority'), table_name='vulnerabilities')
    op.create_index('ix_vulnerabilities_org_cve_source', 'vulnerabilities', ['org_id', 'cve_id', 'source', 'source_id'], unique=False)
    op.drop_column('vulnerabilities', 'scored_at')
    op.drop_column('vulnerabilities', 'enc_score_rationale')
    op.drop_column('vulnerabilities', 'triage_priority')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
